server:
  port: 8082

spring:
  application:
    name: reserva-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reserva_db
    username: app
    password: app
  kafka:
    bootstrap-servers: localhost:29092

    consumer:
      group-id: reserva-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    properties:
      spring.json.use.type.headers: false
      spring.json.trusted.packages: "*"
      spring.json.value.default.type: java.lang.Object

    listener:
      ack-mode: manual

app:
  kafka:
    source: reserva-service
    consumer:
      group-id: reserva-service
    topics:
      reserva-events: reserva.events
      aereo-events: aereo.events
      pagamento-events: pagamento.events
      cliente-validation: cliente.validation

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springdoc: DEBUG
    org.springframework.web.reactive.resource: DEBUG