server:
  port: 8082

spring:
  application:
    name: reserva-service
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/reserva_db
    username: app
    password: app

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.r2dbc: DEBUG
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springdoc: DEBUG
    org.springframework.web.reactive.resource: DEBUG